#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --gpus=1
#SBATCH --time=00:59:59
#SBATCH --output=./%x-%j.out
#SBATCH --error=./%x-%j.err

set -e

module purge
module load 2023
module load Miniconda3/23.5.2-0
module load CUDA/12.1.1


# Activate your environment
source activate IEinAI_env

CUDA_VISIBLE_DEVICES=0 PYTHONPATH=./:$PYTHONPATH python3 baselines/ViT/imagenet_seg_eval.py "$@"